[package]
name = "texture_tool"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "texture_tool"
path = "src/main.rs"

[dependencies]
digest = "0.10"
clap = { version = "4", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "gif", "bmp", "tiff"] }
md-5 = "0.10"
rustdct = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.10"
sha2 = "0.10"
tempfile = "3"
rayon = "1"
walkdir = "2"
